### ISSUE TITLE
Seed database after migration

### ISSUE THREAD

**Issue by SebeeDev** [czworcaInformatyczna/wsb2022-rb6-backend#8]
@CichockiMateusz - Could you add `php artisan db:seed` after `php artisan migrate` during test phase?
It will add example data so tests can be properly executed

**Comment by CichockiMateusz** [comment]
I think it will be good now but tests are still failing becouse it looks like AssetSeeder has problem with enums. Could you look at this @SebeeDev ?

**Comment by SebeeDev** [comment]
As far as I can see tests are failing because enums were added in PHP 8.1 but we are using PHP 8.0

```yaml
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
```
https://github.com/czworcaInformatyczna/wsb2022-rb6-backend/blob/7e73bc588e2f8c52233f5fecf7eaac14346dafff/.github/workflows/laravel.yml

So please change PHP version to 8.1 @CichockiMateusz
